language: php

notifications:
  email:
    recipients:
    - daniel.roperto@catalyst-au.net

sudo: false

services:
- redis-server

cache:
  directories:
  - $HOME/.composer/cache

php:
- 5.5
- 5.6
- 7.0

env:
  matrix:
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=master

addons:
  apt:
    packages:
    - redis-server
    - ruby
    - realpath

before_install:
- pecl install redis
- php -m
- php -r 'echo "Version=".phpversion("redis")." Redis=".class_exists("Redis")." RedisCluster=".class_exists("RedisCluster");'
- gem install redis
- phpenv config-rm xdebug.ini
- cd ../..
- composer selfupdate
- composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
- moodle-plugin-ci -vvv install
- moodle-plugin-ci add-config 'define("TEST_CACHESTORE_ADVREDIS_TESTSERVERS", "127.0.0.1");'
- moodle-plugin-ci add-config 'define("TEST_CACHESTORE_ADVREDIS_TESTSERVERSCLUSTER", "localhost:7000,localhost:7001,localhost:7002");'
- moodle/cache/stores/redis/tests/travis/create-cluster.sh

script:
- moodle-plugin-ci phplint
- moodle-plugin-ci phpcpd
- moodle-plugin-ci phpmd
- moodle-plugin-ci codechecker
- moodle-plugin-ci csslint
- moodle-plugin-ci shifter
- moodle-plugin-ci jshint
- moodle-plugin-ci validate
- moodle-plugin-ci phpunit
- moodle-plugin-ci behat
#- cd moodle ; vendor/bin/phpunit --testsuite cachestore_advredis_testsuite -v # Shows failure/skipped reasons.

after_script:
- killall -9 redis-server
