language: php

notifications:
  email:
    recipients:
    - daniel.roperto@catalyst-au.net

sudo: false

services:
- redis-server

cache:
  directories:
  - $HOME/.composer/cache

php:
- 5.5
- 5.6
- 7.0

env:
  global:
  - MOODLE_BRANCH=MOODLE_31_STABLE
  matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
- phpenv config-rm xdebug.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- cd ../..
- composer selfupdate
- composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
- export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
- php -m
- php -r 'echo "Version=".phpversion("redis")." Redis=".class_exists("Redis")." RedisCluster=".class_exists("RedisCluster");'

install:
- moodle-plugin-ci -vvv install
- moodle-plugin-ci add-config 'define("TEST_CACHESTORE_REDIS_TESTSERVERS", "127.0.0.1");'

script:
- moodle-plugin-ci phplint
- moodle-plugin-ci phpcpd
- moodle-plugin-ci phpmd
- moodle-plugin-ci codechecker
- moodle-plugin-ci csslint
- moodle-plugin-ci shifter
- moodle-plugin-ci jshint
- moodle-plugin-ci validate
- moodle-plugin-ci phpunit
- moodle-plugin-ci behat
# - cd moodle ; vendor/bin/phpunit --testsuite cachestore_redis_testsuite -v # Shows failure/skipped reasons.
